### ISSUE TITLE
Anzeige der Außentemperatur

### ISSUE THREAD

**Issue by kinofreund** [MadErstam/ioBroker.controme#14]
Hallo,
zuerst einmal - toller Job, den Du da gemacht hast.
Wenn ich die API richtig studiert habe, bietet Controme die Außentemperatur, die vom Fühler gemessen wird auch an.
Es wäre sehr schön, wenn Du diesen Wert in den Adapter einbringen könntest.

der kinofreund

**Comment by MadErstam** [comment]
Hi Kinofreund,

entschuldige die späte Rückmeldung. Der Adapter ließt alle Sensoren aus, die einen Raum zugeordnet wurden. Wenn du den Außentemperatursensor einem Raum zuordnest, z.B. dem Heizraum oder dem Raum Außen, wird der Sensor automatisch mit abgefragt.

Viele Grüße!

Marc

**Comment by kinofreund** [comment]
Lieber Marc,

vielen Dank für den Tipp!

 

Beste Grüße

 

sVen

 

___________________________

Kino-Film-Service

Inh. Sven Andresen

Freibadstr. 1a 

14806 Bad Belzig                            

Tel. 033 846 / 905 175      

Fax  033 846 / 905 176

 

Von: MadErstam ***@***.***> 
Gesendet: Freitag, 15. April 2022 11:11
An: MadErstam/ioBroker.controme ***@***.***>
Cc: kinofreund ***@***.***>; Author ***@***.***>
Betreff: Re: [MadErstam/ioBroker.controme] Anzeige der Außentemperatur (Issue #14)

 

Hi Kinofreund,

entschuldige die späte Rückmeldung. Der Adapter ließt alle Sensoren aus, die einen Raum zugeordnet wurden. Wenn du den Außentemperatursensor einem Raum zuordnest, z.B. dem Heizraum oder dem Raum Außen, wird der Sensor automatisch mit abgefragt.

Viele Grüße!

Marc
