### ISSUE TITLE
Set Temperature

### ISSUE THREAD

**Issue by Chesterw83** [MadErstam/ioBroker.controme#2]
Über den Iobroker gesetzte Temperatur Sollwerte werden nach kurzer Zeit wieder auf den vorherigen Wert (Wert der in der Controme Oberfläche gesetzt wurde) zurück gesetzt.
Lesen der Raumtemperaturen funktioniert bisher zuverlässig.

**Comment by MadErstam** [comment]
Der Fehler ist behoben, bitte den Adapter einmal neu installieren und noch einmal testen.

**Comment by Chesterw83** [comment]
Leider hat sich an dem Zustand nichts verändert.
Nach ca. 30 Sekunden wir ein im Iobroker gesetzter Sollwert vom Ursprungssollwert aus der Controme Oberfläche überschrieben.

**Comment by MadErstam** [comment]
Kannst du Mal die Instanz vom Adapter mit Log Level Debug starten und schauen, welche Nachricht im Log steht, wenn du den Wert änderst?

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________

**Comment by Chesterw83** [comment]
Hab eben nochmal mit debug neu installiert. Jetzt scheint es doch richtig zu laufen.
Klarer Anwenderfehler von mir :-)
Planst du noch weitere Objekte für den Adapter.
Super wären die Ausgänge vom Gateway zu den Ventilen um zu sehen welche Heizkreise aktiv sind.

**Comment by MadErstam** [comment]
Sehr schön, das es jetzt funktioniert! Was weitere Objekte angeht, habe ich die Diskussion in ein separates Issue verschoben.
