### ISSUE TITLE
New Features

### ISSUE THREAD

**Issue by MadErstam** [MadErstam/ioBroker.controme#3]
Hab eben nochmal mit debug neu installiert. Jetzt scheint es doch richtig zu laufen.
Klarer Anwenderfehler von mir :-)
Planst du noch weitere Objekte für den Adapter.
Super wären die Ausgänge vom Gateway zu den Ventilen um zu sehen welche Heizkreise aktiv sind.

_Originally posted by @Chesterw83 in https://github.com/MadErstam/ioBroker.controme/issues/2#issuecomment-795879787_

**Comment by MadErstam** [comment]
Was die Heizkreise angeht, schau dir bitte mal die API an, was diese Information eigentlich bringt. Ich finde die zurückgelieferten Informationen (Heizkreis offen oder geschlossen) ziemlich sinnfrei, weil jeglicher Kontext fehlt (und insbesondere auch die erweiterten KI-Informationen nicht übermittelt werden). Gesteuert werden kann über die Heizkreise eh nichts, es dient also lediglich zur Visualisierung (und das macht das Controme-UI ja eigentlich ganz gut).

Um das auszulesen, müsste ich zunächst die MAC-Adressen aller Gateways in den Einstellungen erfassen und könnte diese dann die jeweiligen Ausgänge jeweils als Binärwert (offen, zu) zurückgeben. Aber, wie gesagt, ohne Zuordnung zu Räumen.

Ich frage mal beim Controme-Support an, ob die API in dieser Beziehung nicht mehr liefern kann.

**Comment by ordo01** [comment]
Den Zustand der Ausgänge für alle Räume kann einfach abgefragt werden und im JSON sind sowohl Raum als auch Zustand des Ausgangs enthalten.
http://contromeminiserver/get/json/V1/1/outs/
Der Request liefert ein JSON im folgenden Format zurück:
[
    {
        "etagenname": "EG",
        "id": 1,
        "raeume": [
            {
                "ausgang": {
                    "3": 0
                },
                "id": 1,
                "name": "Bad"
            },
            {
                "ausgang": {
                    "1": 0,
                    " 2": 0
                },
                "id": 2,
                "name": "Küche"
            }
        ]
    }
]

**Comment by MadErstam** [comment]
Hallo Ordo!

Ja, das stimmt, aber leider ist das nur aussagekräftig, wenn man nur ein Gateway hat. Die Ausgänge der anderen Gateways haben nämlich die selben Nummern.

Viele Grüße!

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by ordo01** [comment]
Hallo MadErstam,

danke für die Info, das habe ich mit einem Gateway noch nicht bemerkt. :-(
Die Funktion wäre hilfreich um z.B. die Funktion des Miniservers zu überwachen und ein Gateway Problem frühzeitig zu erkennen
Wenn die Solltemperatur eine gewisse Zeit über der aktuellen Temperatur liegt und kein Ausgang schaltet, dann könnte ein Alarm ausgelöst werden. Die Erkennung wäre wesentlich schneller als die eventuell nicht ansteigende Temperatur zu erkennen.

Grüße

**Comment by loemic87** [comment]
Hey @MadErstam ,

Danke für deine Arbeit mit dem Adapter! 
Bezüglich der Ausgänge zu den Stellmotoren hast du Recht. Das wäre nur für die Visualisierung.

Aber gerade da möchte ich ansetzen: ich würde die Zustände der Motoren gerne in meine Visualisierung einbauen. Ist der Aufwand für dich vertretbar, das mit einzupflegen in den Adapter? 
Ich habe hier auch 2 Gateways, weshalb die json alternative wohl für mich nicht in Frage kommt, oder?

Danke auf jeden Fall für deine Arbeit! Daumen hoch!

**Comment by meicker** [comment]
Hallo MadErstam,
ich hoffe das nachfolgende ist OK für Dich ... Ich dachte es hilft denjenigen die die Ausgänge visualisieren wollen ...

Hallo loemic87,
ich habe das für mich über ein Javascript gelöst. Die Datenpunkte werden dann im Javascript Adapter angelegt: Javascript.0.controme....

```
createState('javascript.0.Controme.hkv.out-1', 0, {type: 'boolean', unit: ''});
createState('javascript.0.Controme.hkv.out-2', 0, {type: 'boolean', unit: ''});
createState('javascript.0.Controme.hkv.out-3', 0, {type: 'boolean', unit: ''});
createState('javascript.0.Controme.hkv.out-4', 0, {type: 'boolean', unit: ''});
createState('javascript.0.Controme.hkv.out-5', 0, {type: 'boolean', unit: ''});
createState('javascript.0.Controme.hkv.out-6', 0, {type: 'boolean', unit: ''});
createState('javascript.0.Controme.hkv.out-7', 0, {type: 'boolean', unit: ''});
createState('javascript.0.Controme.hkv.out-8', 0, {type: 'boolean', unit: ''});
createState('javascript.0.Controme.hkv.out-9', 0, {type: 'boolean', unit: ''});
createState('javascript.0.Controme.hkv.out-10', 0, {type: 'boolean', unit: ''});
createState('javascript.0.Controme.hkv.out-11', 0, {type: 'boolean', unit: ''});
createState('javascript.0.Controme.hkv.out-12', 0, {type: 'boolean', unit: ''});
createState('javascript.0.Controme.hkv.out-13', 0, {type: 'boolean', unit: ''});
createState('javascript.0.Controme.hkv.out-14', 0, {type: 'boolean', unit: ''});
createState('javascript.0.Controme.hkv.out-15', 0, {type: 'boolean', unit: ''});

const url = 'http://192.168.xxx.xxx/get/xx-b2-xx-01-1d-xx/all/';
const dpPath = 'javascript.0.Controme.hkv.out-'; // 15 Datenpunkte Z1 ... Z15, Typ "boolean" 

 

schedule('* * * * *', function() { // jede Minute

   request(url, function(error, response, result) {

      result = result.substring(1, result.indexOf('>')); // < und > entfernen

      let arr = result.split(';');

      for(let i = 0; i < arr.length; i++) {

         setState(dpPath + (i + 1), !!parseInt(arr[i]), true);

      }

   });

});
```
Du musst nur bei const url Deine IP und die Mac Adresse eintragen. Das ist ein Workaround für die Visualisierung solange das im Adapter nicht gelöst ist. Aber im Grunde reicht das auch so ohne im Adapter implementiert sein zu müssen ...

vg
Marc

**Comment by loemic87** [comment]
@meicker Vielen Dank für das Script! Habe für jeden meiner Gateways ein Script aktiviert. Was soll ich sagen: es funktioniert! Vielen Dank!

**Comment by meicker** [comment]
gerne ☺️ 

Viele Grüsse,
Marc

**Comment by MadErstam** [comment]
Das Abfragen der Ausgänge für die Räume und die einzelnen Gateways ist in v0.3 implementiert. Bitte testet das mal.

**Comment by meicker** [comment]
Sehr nice :-) Danke !

Installiert und getestet. Scheint OK zu sein …

vg
Marc
