### ISSUE TITLE
Aktuelle Raumtemperatur setzen

### ISSUE THREAD

**Issue by jump2021** [MadErstam/ioBroker.controme#4]
Hallo zusammen,

kurze Frage.
Ich habe den Adapter im Infobroker erfolgreich einbinden können.
Meine Räume etc. wurden auch super in den iobroker übernommen.

Bei Controme hatte ich angefragt, ob es eine Möglichkeit gibt, die aktuellen Temperaturen der Räume die ich über bestehende Raumtemperatursensoren schon habe über die API an den Contromeserver zu übergeben.

Dazu habe ich einen "virtuelle" Sensorid bekommen, die ich als Raumsensor nun z.B. dem Wohnzimmer zugeordnet habe.

Laut Controme sollte dies nun mit mini-server-ip/set/sensor-ID/temperatur möglich sein.
Kann das ggf. in diesen Adapter mit integriert werden, so dass ich die Temperaturen der Räume die ich im Infobroker habe,
dann in Controme übergeben kann?

Ist also ehr ein enhancement  :-)

Vielen Dank für eine kurze Rückmeldung.

Gruß

Jonas

**Comment by MadErstam** [comment]
Hi Jonas,

cool! Ich habe bisher noch nicht mit virtuellen Sensoren gearbeitet, sondern habe mir mit einem ESP32 ein 1Wire-Device gebaut und spiele darüber die Werte an Controme zurück. Aber das mit den virtuellen Sensoren kann ich gerne einbauen.

Ich hole mir auch mal einen virtuellen Sensor, dann kann ich das auch lokal testen.

Viele Grüße!

Marc

Von: jump2021
Gesendet: Montag, 15. März 2021 15:57
An: MadErstam/ioBroker.controme
Cc: Subscribed
Betreff: [MadErstam/ioBroker.controme] Aktuelle Raumtemperatur setzen (#4)

Hallo zusammen,
kurze Frage.
Ich habe den Adapter im Infobroker erfolgreich einbinden können.
Meine Räume etc. wurden auch super in den iobroker übernommen.
Bei Controme hatte ich angefragt, ob es eine Möglichkeit gibt, die aktuellen Temperaturen der Räume die ich über bestehende Raumtemperatursensoren schon habe über die API an den Contromeserver zu übergeben.
Dazu habe ich einen "virtuelle" Sensorid bekommen, die ich als Raumsensor nun z.B. dem Wohnzimmer zugeordnet habe.
Laut Controme sollte dies nun mit mini-server-ip/set/sensor-ID/temperatur möglich sein.
Kann das ggf. in diesen Adapter mit integriert werden, so dass ich die Temperaturen der Räume die ich im Infobroker habe,
dann in Controme übergeben kann?
Ist also ehr ein enhancement :-)
Vielen Dank für eine kurze Rückmeldung.
Gruß
Jonas

**Comment by Gwenselah** [comment]
Hi
> Dazu habe ich einen "virtuelle" Sensorid bekommen, die ich als Raumsensor nun z.B. dem Wohnzimmer zugeordnet habe.

Will Controme dafür immer noch Geld sehen?

> sondern habe mir mit einem ESP32 ein 1Wire-Device gebaut und spiele darüber die Werte an Controme zurück

Das habe ich nicht verstanden, wie Du das meinst. Du hast Dir mit einem ESP32 und einem Sensor, bspw. BME280 ein Device gebaut. Aber wie spielst Du die Werte an Controme zurück?

**Comment by MadErstam** [comment]
Hi Gwenselah!

Ich nutze einen ESP32 als virtuelles 1Wire-Device, der mit dem Sensorverteiler verbunden ist, Der ESP ist angeschlossen, wie ein normaler Sensor. Er tut so, als wäre er Standard-Sensor, mit dem Controme etwas anfangen kann. Dafür nutze ich die Library OneWireHub.h. Über diese kann ich beliebig viele (aktuell nutze ich 4, mag sein, dass es da von Controme eine Obergrenze gibt) 1Wire-Temperatursensoren simulieren.

Die Temperaturvorgaben der virtuellen 1Wire-Sensoren setze ich per ioBroker basierend auf verschiedenen HmIP-Thermostaten und anderen Quellen.

Da die 1Wire-IDs, die von Controme akzeptiert werden, Standard-IDs sind, lassen sich diese einfach generieren: https://www.tm3d.de/elektronik-projekte/1-wire-simulation-v2/berechung-1-wire-id#idc.

Wenn du weitere Fragen hast, melde dich einfach per Email. Dieses Issue hier ist wohl nicht der geeignete Platz, zumal das mit dem Adapter auch nichts zu tun hat.

Viele Grüße!

Marc

**Comment by Gwenselah** [comment]
Hallo Marc,

ich probiere es mal auf diesem Weg.

Gibt es irgendwo eine Projektbeschreibung, wie Du das realisiert hast?

Die Sensorenverteiler nutze ich auch, genügend freie Steckplätze habe ich noch

Viele Grüße
Andy
________________________________
Von: MadErstam ***@***.***>
Gesendet: Mittwoch, 17. März 2021 14:35
An: MadErstam/ioBroker.controme ***@***.***>
Cc: Andreas Badur ***@***.***>; Comment ***@***.***>
Betreff: Re: [MadErstam/ioBroker.controme] Aktuelle Raumtemperatur setzen (#4)


Hi Gwenselah!

Ich nutze einen ESP32 als virtuelles 1Wire-Device, der mit dem Sensorverteiler verbunden ist, Der ESP ist angeschlossen, wie ein normaler Sensor. Er tut so, als wäre er Standard-Sensor, mit dem Controme etwas anfangen kann. Dafür nutze ich die Library OneWireHub.h. Über diese kann ich beliebig viele (aktuell nutze ich 4, mag sein, dass es da von Controme eine Obergrenze gibt) 1Wire-Temperatursensoren simulieren.

Die Temperaturvorgaben der virtuellen 1Wire-Sensoren setze ich per ioBroker basierend auf verschiedenen HmIP-Thermostaten und anderen Quellen.

Da die 1Wire-IDs, die von Controme akzeptiert werden, Standard-IDs sind, lassen sich diese einfach generieren: https://www.tm3d.de/elektronik-projekte/1-wire-simulation-v2/berechung-1-wire-id#idc.

Wenn du weitere Fragen hast, melde dich einfach per Email. Dieses Issue hier ist wohl nicht der geeignete Platz, zumal das mit dem Adapter auch nichts zu tun hat.

Viele Grüße!

Marc

**Comment by MadErstam** [comment]
Hi Andy,

Ich kann dir gerne morgen Mal ein Foto und das Skript schicken. Du brauchst nur einen Eingang für mehrere Sensoren. Ich habe heute noch auf 6 Sensoren aufgerüstet, das läuft alles über einen Anschluss.

Viele Grüße!

Marc

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by MadErstam** [comment]
Hi Andy,

ich habe gerade festgestellt, dass sich jegliche Sensoren per API setzen lassen. Mein Umweg über einen simulierten Sensor ist also überflüssig. Und Sensor-IDs lassen sich einfach generieren, den Link hatte ich ja unten gepostet. Dafür braucht man nicht 10 € an Controme zu bezahlen. Es scheint sogar so zu sein, als würde Controme die Checksumme, die die letzten 2 Byte des ID sind, völlig ignorieren.

Und im Forum habe ich gelesen, dass die Aktivierung der API auch nicht nötig ist.

Ich implementiere gerade weitere Objekte (die Sensoren) und werde dann auch das Setzen von Zieltemperatur sowie Sensoren mit implementieren. Wird aber noch etwas dauern (1-2 Tage vermutlich).

Viele Grüße!

Marc

Von: Gwenselah ***@***.***>
Gesendet: Mittwoch, 17. März 2021 20:24
An: MadErstam/ioBroker.controme ***@***.***>
Cc: MadErstam ***@***.***>; Assign ***@***.***>
Betreff: Re: [MadErstam/ioBroker.controme] Aktuelle Raumtemperatur setzen (#4)

Hallo Marc,

ich probiere es mal auf diesem Weg.

Gibt es irgendwo eine Projektbeschreibung, wie Du das realisiert hast?

Die Sensorenverteiler nutze ich auch, genügend freie Steckplätze habe ich noch

Viele Grüße
Andy
________________________________
Von: MadErstam ***@***.***<mailto:***@***.***>>
Gesendet: Mittwoch, 17. März 2021 14:35
An: MadErstam/ioBroker.controme ***@***.***<mailto:***@***.***>>
Cc: Andreas Badur ***@***.***<mailto:***@***.***>>; Comment ***@***.***<mailto:***@***.***>>
Betreff: Re: [MadErstam/ioBroker.controme] Aktuelle Raumtemperatur setzen (#4)


Hi Gwenselah!

Ich nutze einen ESP32 als virtuelles 1Wire-Device, der mit dem Sensorverteiler verbunden ist, Der ESP ist angeschlossen, wie ein normaler Sensor. Er tut so, als wäre er Standard-Sensor, mit dem Controme etwas anfangen kann. Dafür nutze ich die Library OneWireHub.h. Über diese kann ich beliebig viele (aktuell nutze ich 4, mag sein, dass es da von Controme eine Obergrenze gibt) 1Wire-Temperatursensoren simulieren.

Die Temperaturvorgaben der virtuellen 1Wire-Sensoren setze ich per ioBroker basierend auf verschiedenen HmIP-Thermostaten und anderen Quellen.

Da die 1Wire-IDs, die von Controme akzeptiert werden, Standard-IDs sind, lassen sich diese einfach generieren: https://www.tm3d.de/elektronik-projekte/1-wire-simulation-v2/berechung-1-wire-id#idc.

Wenn du weitere Fragen hast, melde dich einfach per Email. Dieses Issue hier ist wohl nicht der geeignete Platz, zumal das mit dem Adapter auch nichts zu tun hat.

Viele Grüße!

Marc

**Comment by Gwenselah** [comment]
Hallo Marc,

vielen Dank für deinen Input. Ich teste dann gerne gegen.
Als ich angefangen habe, musste ich zum setzen der Offsets per API diese erwerben. Das hat nicht funktioniert.

Viele Grüße
Andy


________________________________
Von: MadErstam ***@***.***>
Gesendet: Thursday, March 18, 2021 12:02:56 PM
An: MadErstam/ioBroker.controme ***@***.***>
Cc: Andreas Badur ***@***.***>; Comment ***@***.***>
Betreff: Re: [MadErstam/ioBroker.controme] Aktuelle Raumtemperatur setzen (#4)


Hi Andy,

ich habe gerade festgestellt, dass sich jegliche Sensoren per API setzen lassen. Mein Umweg über einen simulierten Sensor ist also überflüssig. Und Sensor-IDs lassen sich einfach generieren, den Link hatte ich ja unten gepostet. Dafür braucht man nicht 10 € an Controme zu bezahlen. Es scheint sogar so zu sein, als würde Controme die Checksumme, die die letzten 2 Byte des ID sind, völlig ignorieren.

Und im Forum habe ich gelesen, dass die Aktivierung der API auch nicht nötig ist.

Ich implementiere gerade weitere Objekte (die Sensoren) und werde dann auch das Setzen von Zieltemperatur sowie Sensoren mit implementieren. Wird aber noch etwas dauern (1-2 Tage vermutlich).

Viele Grüße!

Marc

Von: Gwenselah ***@***.***>
Gesendet: Mittwoch, 17. März 2021 20:24
An: MadErstam/ioBroker.controme ***@***.***>
Cc: MadErstam ***@***.***>; Assign ***@***.***>
Betreff: Re: [MadErstam/ioBroker.controme] Aktuelle Raumtemperatur setzen (#4)

Hallo Marc,

ich probiere es mal auf diesem Weg.

Gibt es irgendwo eine Projektbeschreibung, wie Du das realisiert hast?

Die Sensorenverteiler nutze ich auch, genügend freie Steckplätze habe ich noch

Viele Grüße
Andy
________________________________
Von: MadErstam ***@***.***<mailto:***@***.***>>
Gesendet: Mittwoch, 17. März 2021 14:35
An: MadErstam/ioBroker.controme ***@***.***<mailto:***@***.***>>
Cc: Andreas Badur ***@***.***<mailto:***@***.***>>; Comment ***@***.***<mailto:***@***.***>>
Betreff: Re: [MadErstam/ioBroker.controme] Aktuelle Raumtemperatur setzen (#4)


Hi Gwenselah!

Ich nutze einen ESP32 als virtuelles 1Wire-Device, der mit dem Sensorverteiler verbunden ist, Der ESP ist angeschlossen, wie ein normaler Sensor. Er tut so, als wäre er Standard-Sensor, mit dem Controme etwas anfangen kann. Dafür nutze ich die Library OneWireHub.h. Über diese kann ich beliebig viele (aktuell nutze ich 4, mag sein, dass es da von Controme eine Obergrenze gibt) 1Wire-Temperatursensoren simulieren.

Die Temperaturvorgaben der virtuellen 1Wire-Sensoren setze ich per ioBroker basierend auf verschiedenen HmIP-Thermostaten und anderen Quellen.

Da die 1Wire-IDs, die von Controme akzeptiert werden, Standard-IDs sind, lassen sich diese einfach generieren: https://www.tm3d.de/elektronik-projekte/1-wire-simulation-v2/berechung-1-wire-id#idc.

Wenn du weitere Fragen hast, melde dich einfach per Email. Dieses Issue hier ist wohl nicht der geeignete Platz, zumal das mit dem Adapter auch nichts zu tun hat.

Viele Grüße!

Marc

**Comment by MadErstam** [comment]
Ich habe soeben eine neue Version 0.2.0 released, die das Lesen und Schreiben von Offsets und Sensoren ermöglicht. Über Feedback würde ich mich freuen!

**Comment by jump2021** [comment]
Hallo Marc,

 

ich muss leider ein etwas blöde Frage stellen.

 

Hab in meinem Iobroker die Version 0.1.0 installiert.

 

Wie kann ich denn jetzt auf die aktuelle Version 0.2.0 aktualisieren?

 

Danke für eine kurze Rückmeldung.

 

Gruß

 

Jonas 

 

Von: MadErstam ***@***.***> 
Gesendet: Mittwoch, 17. März 2021 21:26
An: MadErstam/ioBroker.controme ***@***.***>
Cc: jump2021 ***@***.***>; Author ***@***.***>
Betreff: Re: [MadErstam/ioBroker.controme] Aktuelle Raumtemperatur setzen (#4)

 

Hi Andy,

Ich kann dir gerne morgen Mal ein Foto und das Skript schicken. Du brauchst nur einen Eingang für mehrere Sensoren. Ich habe heute noch auf 6 Sensoren aufgerüstet, das läuft alles über einen Anschluss.

Viele Grüße!

Marc

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by MadErstam** [comment]
Hi Jonas,

ist keine doofe Frage: Du gehst in deinem ioBroker auf die Adapter-Seite, wählst da das Icon, was aussieht, wie eine Katze im Kreis (zwischen dem Update-Icon und dem Expert-Icon; beschriftet mit "Installieren aus eigener URL") und gehst dann im Popup-Fenster oben auf "Beliebig".

Dann gibst du die folgende URL an: https://github.com/MadErstam/iobroker.controme/tarball/main/

Viele Grüße!

Marc

**Comment by jump2021** [comment]
Hi Marc,

 

da bekomm ich folgende Meldungen im iobroker:

 

$ ./iobroker url "https://github.com/MadErstam/iobroker.controme/tarball/main/"

install MadErstam/iobroker.controme#main/

NPM version: 6.14.11

npm install MadErstam/iobroker.controme#main/ --loglevel error --prefix "/opt/iobroker" (System call)

npm ERR! code 1

npm ERR! Command failed: git checkout main/

npm ERR! error: Pfadspezifikation 'main/' stimmt mit keinen git-bekannten Dateien überein.npm ERR! 

 

npm ERR! A complete log of this run can be found in:npm ERR!     /opt/iobroker/.npm/_logs/2021-03-24T10_52_06_306Z-debug.log

upload [5] controme.admin /opt/iobroker/node_modules/iobroker.controme/admin/words.js words.js application/javascript

upload [4] controme.admin /opt/iobroker/node_modules/iobroker.controme/admin/tsconfig.json tsconfig.json application/json

upload [3] controme.admin /opt/iobroker/node_modules/iobroker.controme/admin/style.css style.css text/css

upload [2] controme.admin /opt/iobroker/node_modules/iobroker.controme/admin/index_m.html index_m.html text/html

upload [1] controme.admin /opt/iobroker/node_modules/iobroker.controme/admin/controme.png controme.png image/png

upload [0] controme.admin /opt/iobroker/node_modules/iobroker.controme/admin/admin.d.ts admin.d.ts video/mp2t

process exited with code 0

 

sagt Dir das was?

 

Gruß

 

Jonas

 

Von: MadErstam ***@***.***> 
Gesendet: Mittwoch, 24. März 2021 10:24
An: MadErstam/ioBroker.controme ***@***.***>
Cc: jump2021 ***@***.***>; Author ***@***.***>
Betreff: Re: [MadErstam/ioBroker.controme] Aktuelle Raumtemperatur setzen (#4)

 

Hi Jonas,

ist keine doofe Frage: Du gehst in deinem ioBroker auf die Adapter-Seite, wählst da das Icon, was aussieht, wie eine Katze im Kreis (zwischen dem Update-Icon und dem Expert-Icon; beschriftet mit "Installieren aus eigener URL") und gehst dann im Popup-Fenster oben auf "Beliebig".

Dann gibst du die folgende URL an: https://github.com/MadErstam/iobroker.controme/tarball/main/

Viele Grüße!

Marc

**Comment by MadErstam** [comment]
Kannst du mal die folgende URL nehmen: https://github.com/MadErstam/ioBroker.controme/archive/refs/tags/v0.2.1.tar.gz? Dies ist der Direktlink zum letzten Release.

**Comment by jump2021** [comment]
Leider eine ähnliche Meldung:

 

install MadErstam/ioBroker.controme#refs/tags/v0.2.1.tar

NPM version: 6.14.11

npm install MadErstam/ioBroker.controme#refs/tags/v0.2.1.tar --loglevel error --prefix "/opt/iobroker" (System call)

npm ERR! code 1

npm ERR! Command failed: git checkout refs/tags/v0.2.1.tar

npm ERR! error: Pfadspezifikation 'refs/tags/v0.2.1.tar' stimmt mit keinen git-bekannten Dateien überein.npm ERR! 

 

npm ERR! A complete log of this run can be found in:npm ERR!     /opt/iobroker/.npm/_logs/2021-03-24T16_19_26_435Z-debug.log

upload [5] controme.admin /opt/iobroker/node_modules/iobroker.controme/admin/words.js words.js application/javascript

upload [4] controme.admin /opt/iobroker/node_modules/iobroker.controme/admin/tsconfig.json tsconfig.json application/json

upload [3] controme.admin /opt/iobroker/node_modules/iobroker.controme/admin/style.css style.css text/css

upload [2] controme.admin /opt/iobroker/node_modules/iobroker.controme/admin/index_m.html index_m.html text/html

upload [1] controme.admin /opt/iobroker/node_modules/iobroker.controme/admin/controme.png controme.png image/png

upload [0] controme.admin /opt/iobroker/node_modules/iobroker.controme/admin/admin.d.ts admin.d.ts video/mp2t

Update "system.adapter.controme.0"

process exited with code 0

 

Kann den Adapter sonst auch noch mal entfernen und neu einbinden.

 

Gruß

 

Jonas

 

Von: MadErstam ***@***.***> 
Gesendet: Mittwoch, 24. März 2021 15:45
An: MadErstam/ioBroker.controme ***@***.***>
Cc: jump2021 ***@***.***>; Author ***@***.***>
Betreff: Re: [MadErstam/ioBroker.controme] Aktuelle Raumtemperatur setzen (#4)

 

Kannst du mal die folgende URL nehmen: https://github.com/MadErstam/ioBroker.controme/archive/refs/tags/v0.2.1.tar.gz? Dies ist der Direktlink zum letzten Release.

**Comment by MadErstam** [comment]
Hi Jonas,

jetzt bin ich wirklich überfragt. Ich habe es extra noch mal bei meinem Produktivsystem ausprobiert, da hat es problemlos funktioniert.

Viele Grüße!

Marc

**Comment by Gwenselah** [comment]
hast du es mit dieser URL probiert?

https://github.com/MadErstam/iobroker.controme<https://github.com/MadErstam/iobroker.controme/tarball/main/>


so mach ich es immer


________________________________
Von: MadErstam ***@***.***>
Gesendet: Wednesday, March 24, 2021 8:18:24 PM
An: MadErstam/ioBroker.controme ***@***.***>
Cc: Andreas Badur ***@***.***>; Comment ***@***.***>
Betreff: Re: [MadErstam/ioBroker.controme] Aktuelle Raumtemperatur setzen (#4)


Hi Jonas,

jetzt bin ich wirklich überfragt. Ich habe es extra noch mal bei meinem Produktivsystem ausprobiert, da hat es problemlos funktioniert.

Viele Grüße!

Marc

**Comment by jump2021** [comment]
Mit https://github.com/MadErstam/iobroker.controme hat´s nun funktioniert :-)

 

Danke

 

Von: MadErstam ***@***.***> 
Gesendet: Mittwoch, 24. März 2021 15:45
An: MadErstam/ioBroker.controme ***@***.***>
Cc: jump2021 ***@***.***>; Author ***@***.***>
Betreff: Re: [MadErstam/ioBroker.controme] Aktuelle Raumtemperatur setzen (#4)

 

Kannst du mal die folgende URL nehmen: https://github.com/MadErstam/ioBroker.controme/archive/refs/tags/v0.2.1.tar.gz? Dies ist der Direktlink zum letzten Release.

**Comment by jump2021** [comment]
> Controme akzeptiert Standard-Sensor-IDs für die DS18B20 Temperatursensoren. IDs können hier generiert werden: https://www.tm3d.de/elektronik-projekte/1-wire-simulation-v2/berechung-1-wire-id
> 

Guten Abend,

kurze Frage, funktioniert das mit den Sensor-IDs für die DS18B20 Temperatursensoren noch? Wenn ich eine ID generiere und diese dann in Controme als neuen Sensor eintrage, bekomme ich die Meldung "Ungültige Seriennummer"

**Comment by Gwenselah** [comment]
Hallo,

bei mir funktioniert es noch. Einfach die Hexwerte (ohne 0x) nehmen und mit _ verbinden.
VG

**Comment by jump2021** [comment]
> 
> 
> Hallo,
> 
> bei mir funktioniert es noch. Einfach die Hexwerte (ohne 0x) nehmen und mit _ verbinden.
> VG

Hallo, 
mal wieder ein Level 8 Problem.
Hab die ID und nicht die Hexwerte genommen. Nun gehts.
Danke für den Hinweis
