### ISSUE TITLE
3.4 Alpha - Konfiguration: File index_m.html not found

### ISSUE THREAD

**Issue by rbauer77** [MadErstam/ioBroker.controme#43]
Hi Marc,

vielen dank für den erstklassigen Adapter. 

Beim Wechsel von v2.4 auf die neue Alpha habe ich folgendes Problem:

Ein Update auf eine bestehende 2.4 funktioniert nicht korrekt. Der Adapter läuft zwar, allerdings ist in der Konfiguration auf Grund der alten index_m.html keine Eingabemaske für das Gateway vorhanden. Es scheinen auch nicht alle Werte unter Objekte zur Verfügung zu stehen.

Nach Deinstallation der Instanz und des Adapters der Version 2.4 und anschließender Installation der Version 3.4alpha2 und notwendiger manueller (!) Anlage der Instanz kann die Konfigurationsseite nicht geöffnet werden. Es wird mit fehler "File index_m.html not found" quittiert.

![grafik](https://user-images.githubusercontent.com/58787845/184548762-fbbb8e3e-31f7-421d-ae02-5c3da2b596fa.png)

Grund scheinen fehlende Dateien im Ordner Admin zu sein:

![grafik](https://user-images.githubusercontent.com/58787845/184548878-0e086a9c-7c05-4669-94ed-3c56459ac795.png)

1. Alle Instanzen / Adapter von Conteome deinstallieren.
2. Verbliebener Ordner "/opt/iobroker/iobroker-data/files/controme.admin" löschen
3. Controme Adapter 3.4alpha2 in iobroker über Github Installieren
4. Instanz anlegen. => Fehler

 - Adapter version: 3.4alpha2
 - JS-Controller version: 4.0.23
 - Node version: 16.14.2
 - Operating system: RaspberryOS

Kannst du das bitte prüfen und die angepassen Dateien (u.A. index_m.html, etc.) zur Verfügung stellen bzw. ins Setup integrieren?

Vielen dank vorab.

VG
Ralf

**Comment by MadErstam** [comment]
Fixed with latest version
