### ISSUE TITLE
Anbindung von Türkontaktsensoren

### ISSUE THREAD

**Issue by Gwenselah** [MadErstam/ioBroker.controme#5]
Hi,

ich habe mit Hilfe eines Scriptes Türkontaktsensoren einem Raum zugeordnet.

Ist das Fenster geöffnet, wird über einen Raumoffset die berechnete Zieltemperatur um 3 Grad abgesenkt. Ich halte dies für den besseren Wert, als jedes Mal die eigentliche Solltemperatur des Raumes zu verändern. Ich nehme an, dass von Controme diese Art der Wertanpassung anders in ihren Routinen verarbeitet wird; dass die prognostizierende Berechnung dadurch nicht so stark verändert wird. Allerdings muss der Wert alle 10 Minuten aktualisiert werden.

URL zur API-Doku: [Link](https://support.controme.com/api/#set-roomoffset)

**Comment by MadErstam** [comment]
Hi Gwenselah,

ich kann das Setzen des Room-Offsets gerne in einer nächsten Version mit aufnehmen. Aktuell ist der State read-only im Adapter.

Alternativ zum Offset würde sich hierfür wahrscheinlich die Zieltemperatur anbieten, da kann man direkt eine Duration mitgeben. Hier muss ich aber erst schauen, wie ich das umgesetzt bekomme, da ja die Duration kein Datenpunkt in der Objektliste ist.

Viele Grüße!

Marc

**Comment by Gwenselah** [comment]
Hi Marc,

schau Mal hier: [Link](https://support.controme.com/bedienung/#Offset_vs_absolute_Werte) 
Hier wird empfohlen Änderungen über Offsets zu machen und die Solltemperatur möglichst konstant lassen.

Und ganz allgemein ein großes Danke für Deine Mühe.

Viele Grüße
Andy

**Comment by MadErstam** [comment]
Das sollte in der v0.2.0 auch erledigt sein. Zu jedem Raum sind die Offsets aufgeführt, darunter auch die api-Offsets. Im offsets.api-Channel können beliebige States angelegt werden, die dann an den Controme Miniserver übermittelt werden. Standardmäßig legt der Adapter einen api-State an.
