### ISSUE TITLE
API Offset fehlt

### ISSUE THREAD

**Issue by Gwenselah** [MadErstam/ioBroker.controme#6]
Halo Marc,

ich habe eben den Adapter installiert (direkt die 0.2, die 0.1 hatte ich nicht genutzt) und bei keinem meiner Räume wir der API-Offset angezeigt:

![image](https://user-images.githubusercontent.com/47796674/111911401-c36d9200-8a65-11eb-839c-024456bc6b89.png)
Auslesen der States funktioniert aber bisher sauber.

Ich unterstütze gerne beim Debuggen.

Viele Grüße
Andy

**Comment by MadErstam** [comment]
Hi Andy,

den Channel API habe ich nicht selbst generiert, sondern der wurde mir bereits vom Miniserver geliefert. Ich habe darin nur einen State generiert. Wenn das Modul (die werden hier als Channels dargestellt) nicht von vorneherein geliefert wird, legt er darin auch keinen State an.

Warum jetzt mein Server das Api-Modul standardmäßig liefert und deiner nicht, ist mir unklar.

Ich kann aber mal versuchen, einen API-Channel zu generieren, wenn er nicht bereits existiert. Ich teste mal lokal, was der Server dann macht.

Viele Grüße!

Marc

**Comment by MadErstam** [comment]
So, der API-Offset wird jetzt angelegt, wenn er vom Server nicht geliefert wird. Könntest du das mal testen?

**Comment by Gwenselah** [comment]
Hallo Marc,

vielen Dank für die schnelle Umsetzung.
Ich habe eben getestet und dabei ist mir aufgefallen:
- Nach Update über die Github URL ändert sich die Adapterversion nicht, sie bleibt bei 2.0
- Das API Offset wird angezeigt, ein Setzen eines Wertes wird auch an Controme weiter gereicht und dort in die Berechnung einbezogen, aber
   - wird seitens der Controme der Wert dann nach 10 Minuten wieder gelöscht, verbleibt der gesetzte Wert im Objectbaum. Also stimmt die Anzeige, dann nicht mehr mit der Wirklichkeit überein. Zwei Ideen dazu: entweder du schickt den Wert solange in Richtung Controme, solange der Wert im Objektbaum gesetzt ist, oder Du löscht ihm im Objektbaum, sobald Controme ihn auch löscht.
   - wäre es schön, direkt nach Setzen des Offsets per API nochmal einen Read der Werte für den Raum zu bekommen, damit die berechneten Solltemperaturen aktuell sind

Soviel von meiner Seite.

Viele Grüße
Andy

**Comment by MadErstam** [comment]
Nur als Zwischenstand: Ich bin dran und einer Lösung nahe, wird aber noch ein paar Tage dauern, da ich in den Osterferien mich mehr um meine Familie kümmern muss.

**Comment by MadErstam** [comment]
So, das sollte jetzt mit dem neuen Release 0.2.2 behoben sein. 

Die API-Offsets funktionieren jetzt wie folgt:
- Alle Offset-States im Offset-Channel "API" des jeweiligen Raums können geschrieben werden, alle anderen Offset-States sind read-only.
- Es können beliebig viele Offset-States im Offset-Channel "API" angelegt werden. Vom ioBroker werden alle diese States individuell an Controme geschickt und werden im jeweiligen Raum auch einzeln in der UI angezeigt.
- Bei der Abfrage erhalte ich allerdings nur einen konsolidierten Wert im Offset-State "Raum" des Offset-Channels "API" zurück, der alle gelieferten API-States zusammenrechnet.  Daher setze ich beim Update alle Offset-States, für die Controme keinen Wert zurückliefert, auf 0°C, und ergänze den zurückgelieferten State API.Raum.
_Ein Beispiel: Gesetzt wurden die States API.Offset1 = 2°C und API.Offset2 = 1°C. Bei der nächsten Abfrage zeigt ioBroker jetzt 3 States im Offset-Channel "API" an: API.Offset1 = 0°C, API.Offset2 = 0°C und API.raum = 3°C_
- Controme scheint auch erst dann die API-Offsets zurückzusetzen, wenn in keinem der API-Offset-States eine Änderung in den letzten 10 Minuten vorgenommen wurde.

Viele Grüße!

Marc

**Comment by Gwenselah** [comment]
Guten Abend,
hab eben mal selbst getestet. Es hat am Anfang nicht funktioniert, es wurden schlichtweg keine Werte im API Zweig an. Ich musste erst meinen Controme Server von Version 3.12.2020 auf 6.4.2021 aktualisieren.

Das mit dem Offsets, dass nur die Summe aller Einzelwerte zurück geliefert wird, kann ich bestätigen. Auch, dass die Offsets erst zurück gesetzt werden, wenn keiner mehr beschrieben wird.

Daher, denke ich, macht es Sinn, nur mit dem raum-Offset zu arbeiten.

Vielen Dank für Deine Mühe.
Andy

**Comment by MadErstam** [comment]
Hi Andy!

Danke für die Rückmeldung. Dann lasse ich es so, wie es ist. Ich hatte die Version vom 25.03.2021 drauf, damit ging es auch. Wenn es weitere Änderungen in der API gibt, muss ich den Adapter anpassen.

Viele Grüße!

Marc
