### ISSUE TITLE
Adaptername ohne Großbuchstaben

### ISSUE THREAD

**Issue by gerdwolfgang** [MadErstam/ioBroker.controme#7]
Hallo,
habe versucht den Controme-Adapter in ioBroker zu integrieren, endete in Fehlermeldungen.
siehe https://forum.iobroker.net/topic/43971/controme-daten-mit-iobroker-aber-wie
Ein Hinweis im Forum besagt, dass der Adasptername keine Großbuchstaben enthalten darf.
Ich bitte dies zu prüfen und ggf. zu ändern. Vielen Dank

**Describe the bug**  

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by MadErstam** [comment]
Hallo gerdwolfgang,

diverse User nutzen den Adapter in Controme. Insofern dürfte dein Problem, so es nach einem Jahr noch besteht, nicht an Groß- und Kleinschreibung des Namens liegen. Der Adaptername enthält übrigens auch nur Kleinbuchstaben "controme".

Viele Grüße!

Marc
