### ISSUE TITLE
unable to get rooms from the adapter

### ISSUE THREAD

**Issue by bastelbuud** [MadErstam/ioBroker.controme#71]
I use version v.0.3.4 of the adapter. The adapter is really what I was looking for but I have some problems

When starting the adapter, i get the following errors in the logs

controme.0 | 2022-12-04 12:54:19.761 | error | Polling gateway data on 90-b2-e4-0c-14-12 from Controme mini server finished with error "RequestError: getaddrinfo ENOTFOUND http"
controme.0 | 2022-12-04 12:54:16.748 | error | Polling outputs data from Controme mini server finished with error "RequestError: getaddrinfo ENOTFOUND http"
controme.0 | 2022-12-04 12:54:16.728 | error | Polling temperature data from Controme mini server finished with error "RequestError: getaddrinfo ENOTFOUND http"
controme.0 | 2022-12-04 12:54:16.701 | error | Polling gateway data on 90-b2-e4-0c-14-18 from Controme mini server finished with error "RequestError: getaddrinfo ENOTFOUND http"

I have problems with the configuration :
I am able to configure my 2 gateways, but i have then problems with the configuration of the outputs.
I am not able to define gatewayOutsMAC. When i try to define an address here, all the room lines colloapse.
any hints ?

**Comment by MadErstam** [comment]
Not sure what caused that problem, but is likely fixed with latest version
