### ISSUE TITLE
How to install this adapter on my ioBroker?

### ISSUE THREAD

**Issue by Exo84** [MadErstam/ioBroker.controme#90]

**Comment by mcm1957** [comment]
Please ask @MadErstam to request a new addition to ioBroker repositories.

We did not get any responce from him to his request from 2021 the last months. So this ruther old request has been cancelled.
A new request is possible at any time.

https://github.com/ioBroker/ioBroker.repositories/pull/1183

**Comment by MadErstam** [comment]
Fixed
