### ISSUE TITLE
looking for space requirement (dt. Raumanforderung)

### ISSUE THREAD

**Issue by nobbiman** [MadErstam/ioBroker.controme#92]
I'm looking for a way to read out the space requirement (dt. Raumanforderung) 0 or 1 in the ioB adapter. As is well known, the space requirement is set to 0 if there is no need for heat in any of the selected rooms.
Somebody can help me?

**Versions:**  
 - Adapter version: 0.3.4

**Comment by nobbiman** [comment]
Today I can answer my own question with a replacement solution: You can create the “room requirement” data point yourself using a script in which you logically link the respective data point controme.0.<room number>10.outputs.<heating circuit number> for each heating circuit . If all (considered) heating circuit data points are at 0, the space requirement is also 0!
It would be easier to determine the data point from the Controme system via the API, but that's how it works, perhaps the adapter can do that in one of the next versions.

**Comment by MadErstam** [comment]
Hi nobbiman,

sorry for not responding for quite some time. I only maintain the adapter sporadically when I have some time for it. I just published a new version here on Github. Now need to get it published to the adapter list.

Unfortunately, I don't think Controme makes available the heating requirements for a room in the API. Here is the API description: https://support.controme.com/api/. If I overlooked something, please give me a hint.

In fact I have a very similar approach to yours, i.e. setting a data point in iobroker to true of any of the related outputs for that room is active.

Best regards

Marc

**Comment by MadErstam** [comment]
Closing this issue, as the expected API state does note exist
